// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace IronCalc
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "libironcalc_dotnet";





        [DllImport(__DllName, EntryPoint = "from_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ModelContext* from_bytes(byte* buffer, int length, byte* locale, byte* timezone, byte* name);

        [DllImport(__DllName, EntryPoint = "new_empty", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ModelContext* new_empty(byte* locale, byte* timezone);

        [DllImport(__DllName, EntryPoint = "evaluate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void evaluate(ModelContext* context);

        [DllImport(__DllName, EntryPoint = "get_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int get_value(ModelContext* context, int sheet, int row, int col);

        [DllImport(__DllName, EntryPoint = "set_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_value(ModelContext* context, int sheet, int row, int col, int value);

        [DllImport(__DllName, EntryPoint = "dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dispose(ModelContext* context);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ModelContext
    {
    }



}
