// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace IronCalc.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "libironcalc_dotnet";





        [DllImport(__DllName, EntryPoint = "load_from_xlsx_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CreateModelContextResult load_from_xlsx_bytes(byte* buffer, int length, byte* locale, byte* timezone, byte* name);

        [DllImport(__DllName, EntryPoint = "new_empty", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CreateModelContextResult new_empty(byte* name, byte* locale, byte* timezone);

        [DllImport(__DllName, EntryPoint = "evaluate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void evaluate(ModelContext* context);

        [DllImport(__DllName, EntryPoint = "get_cell_value_by_index", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GetValueResult get_cell_value_by_index(ModelContext* context, uint sheet, int row, int col);

        [DllImport(__DllName, EntryPoint = "set_user_input", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ModelContextError* set_user_input(ModelContext* context, uint sheet, int row, int col, byte* value);

        [DllImport(__DllName, EntryPoint = "dispose_cell_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dispose_cell_value(CellValue* value);

        [DllImport(__DllName, EntryPoint = "dispose_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dispose_error(ModelContextError* error);

        [DllImport(__DllName, EntryPoint = "dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dispose(ModelContext* context);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ModelContext
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ModelContextError
    {
        public ModelContextErrorTag tag;
        [MarshalAs(UnmanagedType.U1)] public bool has_message;
        public byte* message;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CreateModelContextResult
    {
        public ModelContext* model;
        public ModelContextError* error;
        [MarshalAs(UnmanagedType.U1)] public bool is_ok;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CellValue
    {
        public CellValueTag tag;
        public byte* string_value;
        public double number_value;
        [MarshalAs(UnmanagedType.U1)] public bool boolean_value;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct GetValueResult
    {
        public CellValue* value;
        public ModelContextError* error;
        [MarshalAs(UnmanagedType.U1)] public bool is_ok;
    }


    internal enum ModelContextErrorTag : uint
    {
        XlsxError = 1,
        WorkbookError = 2,
        SetUserInputError = 3,
        GetUserInputError = 4,
    }

    internal enum CellValueTag : uint
    {
        None = 0,
        String = 1,
        Number = 2,
        Boolean = 3,
    }


}
