[workspace]
resolver = "2"

members = [
  "base",
  "xlsx",
  "bindings/wasm",
  "bindings/python",
]

exclude = [
  "generate_locale",
  "webapp/app.ironcalc.com/server",
]

[profile.release]
lto = true
