"""Type stubs for the ironcalc native extension.

Complex values (styles, conditional formatting rules, themes, ...) cross the
Rust/Python boundary as plain dictionaries with the same shapes used by the
IronCalc wasm bindings. The TypedDicts below describe the most common ones.
"""

from enum import Enum
from typing import Any, TypedDict

__version__: str

class WorkbookError(Exception): ...

class CellType(Enum):
    Number = 1
    Text = 2
    LogicalValue = 4
    ErrorValue = 16
    Array = 64
    CompoundData = 128

# A color is None (no color), an "#RRGGBB" string, or a [theme_index, tint] pair
Color = None | str | list[Any]

class FontDict(TypedDict, total=False):
    strike: bool
    u: bool
    b: bool
    i: bool
    sz: int
    color: Color
    name: str
    family: int
    scheme: str

class FillDict(TypedDict, total=False):
    color: Color

class BorderItemDict(TypedDict):
    style: str  # "thin", "medium", "thick", "double", "dotted", ...
    color: Color

class BorderDict(TypedDict, total=False):
    diagonal_up: bool
    diagonal_down: bool
    left: BorderItemDict | None
    right: BorderItemDict | None
    top: BorderItemDict | None
    bottom: BorderItemDict | None
    diagonal: BorderItemDict | None

class AlignmentDict(TypedDict, total=False):
    horizontal: str  # "left", "center", "right", "justify", ...
    vertical: str  # "top", "center", "bottom", ...
    wrap_text: bool

class StyleDict(TypedDict, total=False):
    alignment: AlignmentDict | None
    num_fmt: str
    fill: FillDict
    font: FontDict
    border: BorderDict
    quote_prefix: bool

class BorderAreaDict(TypedDict):
    item: BorderItemDict
    # "All", "Inner", "Outer", "Top", "Right", "Bottom", "Left",
    # "CenterH", "CenterV" or "None"
    type: str

class DefinedNameDict(TypedDict):
    name: str
    scope: int | None
    formula: str

class SheetPropertiesDict(TypedDict, total=False):
    name: str
    state: str  # "visible", "hidden" or "veryHidden"
    sheet_id: int
    color: Color

class LinkDict(TypedDict, total=False):
    """A cell hyperlink. The link is cell metadata: the text displayed in the
    cell is the cell content, not part of the link.

    External links ({"type": "External"}) have a "target" (an URL, a mailto:
    URI or a file). Internal links ({"type": "Internal"}) have a "location":
    a cell reference like "Sheet1!A30" or a defined name.
    """

    type: str  # "External" or "Internal"
    target: str  # external links only
    location: str  # internal links only
    tooltip: str | None

class CellLinkDict(LinkDict, total=False):
    """A link together with the (row, column) cell it is attached to.

    A dynamic link is created by a formula like HYPERLINK: it cannot be
    edited or deleted, only the formula can change it.
    """

    row: int
    column: int
    dynamic: bool

# Conditional formatting rules, i.e.:
#   {"type": "CellIs", "operator": "GreaterThan", "formula": "5",
#    "formula2": None, "format": {"fill": {"color": "#FFC7CE"}},
#    "stop_if_true": False}
#   {"type": "ColorScale", "thresholds": [{"cfvo": "Min", "color": "#FF0000"},
#    {"cfvo": "Max", "color": "#00FF00"}]}
CfRule = dict[str, Any]

def column_name_from_number(column: int) -> str: ...
def column_number_from_name(column: str) -> int: ...
def quote_name(name: str) -> str: ...
def get_all_timezones() -> list[str]: ...
def get_supported_locales() -> list[str]: ...
def create(
    name: str, locale: str = "en", tz: str = "UTC", language_id: str = "en"
) -> Model: ...
def load_from_xlsx(
    file_path: str, locale: str = "en", tz: str = "UTC", language_id: str = "en"
) -> Model: ...
def load_from_icalc(file_name: str, language_id: str = "en") -> Model: ...
def load_from_bytes(bytes: bytes, language_id: str = "en") -> Model: ...
def create_user_model(
    name: str, locale: str = "en", tz: str = "UTC", language_id: str = "en"
) -> UserModel: ...
def create_user_model_from_xlsx(
    file_path: str, locale: str = "en", tz: str = "UTC", language_id: str = "en"
) -> UserModel: ...
def create_user_model_from_icalc(
    file_name: str, language_id: str = "en"
) -> UserModel: ...
def create_user_model_from_bytes(
    bytes: bytes, language_id: str = "en"
) -> UserModel: ...
def test_panic() -> None: ...

class Model:
    """A workbook with the raw, low level API.

    Nothing is evaluated automatically: call `evaluate` after changes.
    There is no undo/redo history and no diffs are produced.
    """

    # Persistence
    def save_to_xlsx(self, file: str) -> None: ...
    def save_to_icalc(self, file: str) -> None: ...
    def to_bytes(self) -> bytes: ...
    def evaluate(self) -> None: ...

    # Set values
    def set_user_input(self, sheet: int, row: int, column: int, value: str) -> None: ...
    def set_user_array_formula(
        self, sheet: int, row: int, column: int, width: int, height: int, formula: str
    ) -> None: ...
    def update_cell_with_text(
        self, sheet: int, row: int, column: int, value: str
    ) -> None: ...
    def update_cell_with_number(
        self, sheet: int, row: int, column: int, value: float
    ) -> None: ...
    def update_cell_with_bool(
        self, sheet: int, row: int, column: int, value: bool
    ) -> None: ...
    def update_cell_with_formula(
        self, sheet: int, row: int, column: int, formula: str
    ) -> None: ...
    def clear_cell_contents(self, sheet: int, row: int, column: int) -> None: ...
    def range_clear_contents(
        self, sheet: int, start_row: int, start_column: int, end_row: int, end_column: int
    ) -> None: ...
    def range_clear_all(
        self, sheet: int, start_row: int, start_column: int, end_row: int, end_column: int
    ) -> None: ...

    # Get values
    def get_cell_content(self, sheet: int, row: int, column: int) -> str: ...
    def get_cell_formula(self, sheet: int, row: int, column: int) -> str | None: ...
    def get_cell_value(
        self, sheet: int, row: int, column: int
    ) -> None | str | float | bool: ...
    def get_cell_value_by_ref(self, cell_ref: str) -> None | str | float | bool: ...
    def get_cell_type(self, sheet: int, row: int, column: int) -> CellType: ...
    def get_formatted_cell_value(self, sheet: int, row: int, column: int) -> str: ...
    def is_empty_cell(self, sheet: int, row: int, column: int) -> bool: ...
    def get_all_cells(self) -> list[tuple[int, int, int]]: ...
    def get_sheet_markup(self, sheet: int) -> str: ...

    # Styles
    def set_cell_style(
        self, sheet: int, row: int, column: int, style: StyleDict
    ) -> None: ...
    def get_cell_style(self, sheet: int, row: int, column: int) -> StyleDict: ...
    def set_column_style(self, sheet: int, column: int, style: StyleDict) -> None: ...
    def get_column_style(self, sheet: int, column: int) -> StyleDict | None: ...
    def delete_column_style(self, sheet: int, column: int) -> None: ...
    def set_row_style(self, sheet: int, row: int, style: StyleDict) -> None: ...
    def get_row_style(self, sheet: int, row: int) -> StyleDict | None: ...
    def delete_row_style(self, sheet: int, row: int) -> None: ...

    # Rows and columns
    def insert_rows(self, sheet: int, row: int, row_count: int) -> None: ...
    def insert_columns(self, sheet: int, column: int, column_count: int) -> None: ...
    def delete_rows(self, sheet: int, row: int, row_count: int) -> None: ...
    def delete_columns(self, sheet: int, column: int, column_count: int) -> None: ...
    def get_column_width(self, sheet: int, column: int) -> float: ...
    def get_row_height(self, sheet: int, row: int) -> float: ...
    def set_column_width(self, sheet: int, column: int, width: float) -> None: ...
    def set_row_height(self, sheet: int, row: int, height: float) -> None: ...
    def set_column_hidden(self, sheet: int, column: int, hidden: bool) -> None: ...
    def set_row_hidden(self, sheet: int, row: int, hidden: bool) -> None: ...
    def is_column_hidden(self, sheet: int, column: int) -> bool: ...
    def is_row_hidden(self, sheet: int, row: int) -> bool: ...

    # Frozen rows/columns
    def get_frozen_columns_count(self, sheet: int) -> int: ...
    def get_frozen_rows_count(self, sheet: int) -> int: ...
    def set_frozen_columns_count(self, sheet: int, column_count: int) -> None: ...
    def set_frozen_rows_count(self, sheet: int, row_count: int) -> None: ...

    # Sheets
    def get_worksheets_properties(self) -> list[SheetPropertiesDict]: ...
    def set_sheet_color(self, sheet: int, color: Color) -> None: ...
    def set_sheet_state(self, sheet: int, state: str) -> None: ...
    def add_sheet(self, sheet_name: str) -> None: ...
    def new_sheet(self) -> None: ...
    def delete_sheet(self, sheet: int) -> None: ...
    def rename_sheet(self, sheet: int, new_name: str) -> None: ...
    def get_sheet_dimensions(self, sheet: int) -> tuple[int, int, int, int]: ...
    def set_show_grid_lines(self, sheet: int, show_grid_lines: bool) -> None: ...

    # Links
    def get_cell_link(self, sheet: int, row: int, column: int) -> LinkDict | None: ...
    def set_cell_link(
        self, sheet: int, row: int, column: int, link: LinkDict
    ) -> None: ...
    def delete_cell_link(self, sheet: int, row: int, column: int) -> None: ...
    def get_links(self, sheet: int) -> list[CellLinkDict]: ...

    # Defined names
    def get_defined_name_list(self) -> list[DefinedNameDict]: ...
    def new_defined_name(
        self, name: str, scope: int | None, formula: str
    ) -> None: ...
    def update_defined_name(
        self,
        name: str,
        scope: int | None,
        new_name: str,
        new_scope: int | None,
        new_formula: str,
    ) -> None: ...
    def delete_defined_name(self, name: str, scope: int | None) -> None: ...

    # Workbook properties
    def get_theme(self) -> dict[str, Any]: ...
    def set_theme(self, theme: dict[str, Any]) -> None: ...
    def get_timezone(self) -> str: ...
    def set_timezone(self, timezone: str) -> None: ...
    def get_locale(self) -> str: ...
    def set_locale(self, locale: str) -> None: ...
    def get_language(self) -> str: ...
    def set_language(self, language: str) -> None: ...
    def get_fmt_settings(self) -> dict[str, str]: ...
    def test_panic(self) -> None: ...

class UserModel:
    """A workbook with the user, high level API: the same API used by the
    IronCalc web application.

    Every action evaluates the workbook, keeps undo/redo history and produces
    diffs for collaboration.
    """

    def __init__(
        self,
        name: str,
        locale: str = "en",
        tz: str = "UTC",
        language_id: str = "en",
    ) -> None: ...
    @staticmethod
    def from_bytes(bytes: bytes, language_id: str = "en") -> UserModel: ...
    @staticmethod
    def from_xlsx(
        file_path: str, locale: str = "en", tz: str = "UTC", language_id: str = "en"
    ) -> UserModel: ...
    @staticmethod
    def from_icalc(file_name: str, language_id: str = "en") -> UserModel: ...

    # Persistence
    def save_to_xlsx(self, file: str) -> None: ...
    def save_to_icalc(self, file: str) -> None: ...
    def to_bytes(self) -> bytes: ...

    # Collaboration
    def apply_external_diffs(self, external_diffs: bytes) -> None: ...
    def flush_send_queue(self) -> bytes: ...

    # Undo / redo and evaluation
    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def can_undo(self) -> bool: ...
    def can_redo(self) -> bool: ...
    def pause_evaluation(self) -> None: ...
    def resume_evaluation(self) -> None: ...
    def evaluate(self) -> None: ...

    # Workbook properties
    def get_name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def get_timezone(self) -> str: ...
    def set_timezone(self, timezone: str) -> None: ...
    def get_locale(self) -> str: ...
    def set_locale(self, locale: str) -> None: ...
    def get_language(self) -> str: ...
    def set_language(self, language: str) -> None: ...
    def get_fmt_settings(self) -> dict[str, str]: ...
    def get_theme(self) -> dict[str, Any]: ...
    def set_theme(self, theme: dict[str, Any]) -> None: ...
    def resolve_color(self, color: Color) -> str: ...

    # Cell values
    def set_user_input(self, sheet: int, row: int, column: int, value: str) -> None: ...
    def set_user_array_formula(
        self, sheet: int, row: int, column: int, width: int, height: int, formula: str
    ) -> None: ...
    def get_cell_content(self, sheet: int, row: int, column: int) -> str: ...
    def get_formatted_cell_value(self, sheet: int, row: int, column: int) -> str: ...
    def get_cell_type(self, sheet: int, row: int, column: int) -> CellType: ...
    def get_cell_array_structure(
        self, sheet: int, row: int, column: int
    ) -> dict[str, Any] | str: ...
    def get_sheet_dimensions(self, sheet: int) -> tuple[int, int, int, int]: ...

    # Ranges
    def range_clear_all(
        self, sheet: int, start_row: int, start_column: int, end_row: int, end_column: int
    ) -> None: ...
    def range_clear_contents(
        self, sheet: int, start_row: int, start_column: int, end_row: int, end_column: int
    ) -> None: ...
    def range_clear_formatting(
        self, sheet: int, start_row: int, start_column: int, end_row: int, end_column: int
    ) -> None: ...
    def auto_fill_rows(
        self,
        sheet: int,
        start_row: int,
        start_column: int,
        end_row: int,
        end_column: int,
        to_row: int,
    ) -> None: ...
    def auto_fill_columns(
        self,
        sheet: int,
        start_row: int,
        start_column: int,
        end_row: int,
        end_column: int,
        to_column: int,
    ) -> None: ...

    # Sheets
    def new_sheet(self) -> None: ...
    def delete_sheet(self, sheet: int) -> None: ...
    def duplicate_sheet(self, sheet: int) -> None: ...
    def hide_sheet(self, sheet: int) -> None: ...
    def unhide_sheet(self, sheet: int) -> None: ...
    def rename_sheet(self, sheet: int, name: str) -> None: ...
    def move_sheet(self, sheet: int, new_index: int) -> None: ...
    def set_sheet_color(self, sheet: int, color: Color) -> None: ...
    def get_worksheets_properties(self) -> list[SheetPropertiesDict]: ...
    def set_show_grid_lines(self, sheet: int, show_grid_lines: bool) -> None: ...
    def get_show_grid_lines(self, sheet: int) -> bool: ...

    # Links
    def get_cell_link(self, sheet: int, row: int, column: int) -> LinkDict | None: ...
    def set_cell_link(
        self,
        sheet: int,
        row: int,
        column: int,
        link: LinkDict,
        label: str | None = None,
    ) -> None: ...
    def delete_cell_link(self, sheet: int, row: int, column: int) -> None: ...
    def get_links(self, sheet: int) -> list[CellLinkDict]: ...

    # Rows and columns
    def insert_rows(self, sheet: int, row: int, row_count: int) -> None: ...
    def insert_columns(self, sheet: int, column: int, column_count: int) -> None: ...
    def delete_rows(self, sheet: int, row: int, row_count: int) -> None: ...
    def delete_columns(self, sheet: int, column: int, column_count: int) -> None: ...
    def move_columns(
        self, sheet: int, column: int, column_count: int, delta: int
    ) -> None: ...
    def move_rows(self, sheet: int, row: int, row_count: int, delta: int) -> None: ...
    def get_row_height(self, sheet: int, row: int) -> float: ...
    def get_column_width(self, sheet: int, column: int) -> float: ...
    def set_rows_height(
        self, sheet: int, row_start: int, row_end: int, height: float
    ) -> None: ...
    def set_columns_width(
        self, sheet: int, column_start: int, column_end: int, width: float
    ) -> None: ...
    def set_rows_hidden(
        self, sheet: int, row_start: int, row_end: int, hidden: bool
    ) -> None: ...
    def set_columns_hidden(
        self, sheet: int, column_start: int, column_end: int, hidden: bool
    ) -> None: ...
    def get_frozen_rows_count(self, sheet: int) -> int: ...
    def get_frozen_columns_count(self, sheet: int) -> int: ...
    def set_frozen_rows_count(self, sheet: int, count: int) -> None: ...
    def set_frozen_columns_count(self, sheet: int, count: int) -> None: ...
    def get_last_non_empty_in_row_before_column(
        self, sheet: int, row: int, column: int
    ) -> int | None: ...
    def get_first_non_empty_in_row_after_column(
        self, sheet: int, row: int, column: int
    ) -> int | None: ...

    # Styles
    def update_range_style(
        self,
        sheet: int,
        start_row: int,
        start_column: int,
        end_row: int,
        end_column: int,
        style_path: str,
        value: str,
    ) -> None: ...
    def get_cell_style(self, sheet: int, row: int, column: int) -> StyleDict: ...
    def get_extended_cell_style(
        self, sheet: int, row: int, column: int
    ) -> dict[str, Any]: ...
    def on_paste_styles(self, styles: list[list[StyleDict]]) -> None: ...
    def set_area_with_border(
        self,
        sheet: int,
        start_row: int,
        start_column: int,
        end_row: int,
        end_column: int,
        border_area: BorderAreaDict,
    ) -> None: ...

    # Named styles
    def get_named_style_list(self) -> list[str]: ...
    def get_named_style(self, name: str) -> StyleDict: ...
    def get_named_style_includes(self, name: str) -> dict[str, bool]: ...
    def create_named_style(
        self,
        name: str,
        style: StyleDict,
        includes: dict[str, bool] | None = None,
    ) -> None: ...
    def update_named_style(
        self,
        name: str,
        new_name: str,
        style: StyleDict,
        includes: dict[str, bool] | None = None,
    ) -> None: ...
    def delete_named_style(self, name: str) -> None: ...
    def get_builtin_named_styles(self) -> list[dict[str, Any]]: ...
    def on_apply_named_style(self, name: str) -> None: ...

    # Conditional formatting
    def get_conditional_formatting_list(self, sheet: int) -> list[dict[str, Any]]: ...
    def add_conditional_formatting(
        self, sheet: int, range: str, rule: CfRule
    ) -> None: ...
    def update_conditional_formatting(
        self, sheet: int, index: int, new_range: str, new_rule: CfRule
    ) -> None: ...
    def delete_conditional_formatting(self, sheet: int, index: int) -> None: ...
    def get_dxf_for_conditional_formatting(
        self, sheet: int, index: int
    ) -> dict[str, Any] | None: ...
    def raise_conditional_formatting_priority(self, sheet: int, index: int) -> None: ...
    def lower_conditional_formatting_priority(self, sheet: int, index: int) -> None: ...

    # Defined names
    def get_defined_name_list(self) -> list[DefinedNameDict]: ...
    def new_defined_name(self, name: str, scope: int | None, formula: str) -> None: ...
    def update_defined_name(
        self,
        name: str,
        scope: int | None,
        new_name: str,
        new_scope: int | None,
        new_formula: str,
    ) -> None: ...
    def delete_defined_name(self, name: str, scope: int | None) -> None: ...
    def is_valid_defined_name(
        self, name: str, scope: int | None, formula: str
    ) -> None: ...

    # Selection
    def get_selected_sheet(self) -> int: ...
    def get_selected_cell(self) -> tuple[int, int, int]: ...
    def get_selected_view(self) -> dict[str, Any]: ...
    def set_selected_sheet(self, sheet: int) -> None: ...
    def set_selected_cell(self, row: int, column: int) -> None: ...
    def set_selected_range(
        self, start_row: int, start_column: int, end_row: int, end_column: int
    ) -> None: ...

    # Clipboard
    def copy_to_clipboard(self) -> dict[str, Any]: ...
    def paste_from_clipboard(
        self,
        source_sheet: int,
        source_range: tuple[int, int, int, int],
        clipboard: dict[Any, Any],
        is_cut: bool,
    ) -> None: ...
    def paste_csv_string(
        self,
        sheet: int,
        start_row: int,
        start_column: int,
        end_row: int,
        end_column: int,
        csv: str,
    ) -> None: ...
