/* auto-generated by NAPI-RS */
/* eslint-disable */

// Hand-maintained type definitions for the values exchanged with the engine.
// They mirror the serde serialization of the Rust types in ironcalc_base and
// are prepended to the generated index.d.ts (see "dtsHeaderFile" in
// package.json). Keep them in sync with bindings/wasm/types.ts.

/**
 * A cell color value. Matches the Rust `Color` enum serialized with `#[serde(untagged)]`:
 * - `string`           → `Color::Rgb("#RRGGBB")`
 * - `[number, number]` → `Color::Theme(index, tint)`
 * - absent/undefined   → `Color::None` (field omitted via skip_serializing_if)
 *
 * Pass to `model.resolveColor(color)` to get the final CSS hex string.
 */
export type Color = string | [number, number] | undefined;

export type BorderType =
  | "All"
  | "Inner"
  | "Outer"
  | "Top"
  | "Right"
  | "Bottom"
  | "Left"
  | "CenterH"
  | "CenterV"
  | "None";

export type BorderStyle =
  | "thin"
  | "medium"
  | "thick"
  | "double"
  | "dotted"
  | "slantdashdot"
  | "mediumdashed"
  | "mediumdashdotdot"
  | "mediumdashdot";

export interface BorderItem {
  style: BorderStyle;
  color?: Color;
}

export interface BorderArea {
  item: BorderItem;
  type: BorderType;
}

export interface CellStyleFill {
  color?: Color;
}

export interface CellStyleFont {
  u: boolean;
  b: boolean;
  i: boolean;
  strike: boolean;
  sz: number;
  color?: Color;
  name: string;
  family: number;
  scheme: string;
}

export interface CellStyleBorder {
  diagonal_up?: boolean;
  diagonal_down?: boolean;
  left?: BorderItem;
  right?: BorderItem;
  top?: BorderItem;
  bottom?: BorderItem;
  diagonal?: BorderItem;
}

export type VerticalAlignment =
  | "bottom"
  | "center"
  | "distributed"
  | "justify"
  | "top";

export type HorizontalAlignment =
  | "left"
  | "center"
  | "right"
  | "general"
  | "centerContinuous"
  | "distributed"
  | "fill"
  | "justify";

export interface Alignment {
  horizontal: HorizontalAlignment;
  vertical: VerticalAlignment;
  wrap_text: boolean;
}

export interface CellStyle {
  read_only: boolean;
  quote_prefix: boolean;
  fill: CellStyleFill;
  font: CellStyleFont;
  border: CellStyleBorder;
  num_fmt: string;
  alignment?: Alignment;
}

export interface WorksheetProperties {
  name: string;
  /** Tab color. Absent when Color::None. */
  color?: Color;
  sheet_id: number;
  state: string;
}

export type CellArrayStructure =
  | "SingleCell"
  | { DynamicChild: [number, number, number, number] }
  | { DynamicAnchor: [number, number] }
  | { ArrayAnchor: [number, number] }
  | { ArrayChild: [number, number, number, number] };

export type ValueOperator =
  | "Equal"
  | "GreaterThan"
  | "GreaterThanOrEqual"
  | "LessThan"
  | "LessThanOrEqual"
  | "NotEqual"
  | "Between"
  | "NotBetween";

export type TextOperator =
  | "Contains"
  | "DoesNotContain"
  | "BeginsWith"
  | "EndsWith"
  | "Equals";

export type PeriodType =
  | "Between"
  | "NotBetween"
  | "Yesterday"
  | "Today"
  | "Tomorrow"
  | "Last7Days"
  | "Next7Days"
  | "LastWeek"
  | "ThisWeek"
  | "NextWeek"
  | "LastMonth"
  | "ThisMonth"
  | "NextMonth"
  | "LastYear"
  | "ThisYear"
  | "NextYear";

export type Icon =
  | "ArrowUp"
  | "ArrowRight"
  | "ArrowDown"
  | "ArrowAngleUp"
  | "ArrowAngleDown"
  | "Circle"
  | "TriangleUp"
  | "TriangleDown"
  | "FlatRectangle"
  | "Rhombus"
  | "Flag"
  | "Check"
  | "Cross"
  | "Exclamation"
  | "Star"
  | "Heart"
  | "ThumbsUp"
  | "ThumbsDown"
  | "TriangleUpFilled"
  | "TriangleDownFilled";

export type Cfvo =
  | "Min"
  | "Max"
  | { Number: number }
  | { Percent: number }
  | { Percentile: number }
  | { Formula: string };

export interface ColorScaleThreshold {
  cfvo: Cfvo;
  color: Color;
}

export interface IconThreshold {
  icon: Icon;
  cfvo: Cfvo;
  color: Color;
  is_strict: boolean;
}

/** Stored CF rule returned by getConditionalFormattingList (no format field —
 * use getDxfForConditionalFormatting to retrieve it). */
export type CfRule =
  | { type: "ColorScale"; thresholds: ColorScaleThreshold[] }
  | { type: "CellIs"; operator: ValueOperator; formula: string; formula2: string | null; stop_if_true: boolean }
  | { type: "Formula"; formula: string; stop_if_true: boolean }
  | { type: "Text"; operator: TextOperator; value: string; stop_if_true: boolean }
  | { type: "TimePeriod"; time_period: PeriodType; date1: string | null; date2: string | null; stop_if_true: boolean }
  | { type: "DuplicateValues"; stop_if_true: boolean }
  | { type: "UniqueValues"; stop_if_true: boolean }
  | { type: "Blanks"; stop_if_true: boolean }
  | { type: "NotBlanks"; stop_if_true: boolean }
  | { type: "Errors"; stop_if_true: boolean }
  | { type: "NoErrors"; stop_if_true: boolean }
  | { type: "AboveAverage"; stop_if_true: boolean }
  | { type: "BelowAverage"; stop_if_true: boolean }
  | { type: "Top10"; rank: number; percent: boolean; stop_if_true: boolean }
  | { type: "Bottom10"; rank: number; percent: boolean; stop_if_true: boolean }
  | { type: "DataBar"; min: Cfvo | null; max: Cfvo | null; positive_color: Color; negative_color: Color; is_gradient: boolean; show_value: boolean }
  | { type: "IconSet"; thresholds: IconThreshold[]; show_value: boolean }
  | { type: "IconRating"; icon: Icon; color: Color; thresholds: [Cfvo, boolean][]; show_value: boolean };

/** Input CF rule for addConditionalFormatting / updateConditionalFormatting.
 *  Dxf-based variants carry an inline `format` and a `stop_if_true` flag. */
export type CfRuleInput =
  | { type: "ColorScale"; thresholds: ColorScaleThreshold[] }
  | { type: "CellIs"; operator: ValueOperator; formula: string; formula2: string | null; format: Dxf; stop_if_true: boolean }
  | { type: "Formula"; formula: string; format: Dxf; stop_if_true: boolean }
  | { type: "Text"; operator: TextOperator; value: string; format: Dxf; stop_if_true: boolean }
  | { type: "TimePeriod"; time_period: PeriodType; date1: string | null; date2: string | null; format: Dxf; stop_if_true: boolean }
  | { type: "DuplicateValues"; format: Dxf; stop_if_true: boolean }
  | { type: "UniqueValues"; format: Dxf; stop_if_true: boolean }
  | { type: "Blanks"; format: Dxf; stop_if_true: boolean }
  | { type: "NotBlanks"; format: Dxf; stop_if_true: boolean }
  | { type: "Errors"; format: Dxf; stop_if_true: boolean }
  | { type: "NoErrors"; format: Dxf; stop_if_true: boolean }
  | { type: "AboveAverage"; format: Dxf; stop_if_true: boolean }
  | { type: "BelowAverage"; format: Dxf; stop_if_true: boolean }
  | { type: "Top10"; rank: number; percent: boolean; format: Dxf; stop_if_true: boolean }
  | { type: "Bottom10"; rank: number; percent: boolean; format: Dxf; stop_if_true: boolean }
  | { type: "DataBar"; min: Cfvo | null; max: Cfvo | null; positive_color: Color; negative_color: Color; is_gradient: boolean; show_value: boolean }
  | { type: "IconSet"; thresholds: IconThreshold[]; show_value: boolean }
  | { type: "IconRating"; icon: Icon; color: Color; thresholds: [Cfvo, boolean][]; show_value: boolean };

export type FontScheme = "minor" | "major" | "none";

export interface DxfFont {
  strike?: boolean;
  u?: boolean;
  b?: boolean;
  i?: boolean;
  sz?: number;
  color?: Color;
  name?: string;
  family?: number;
  scheme?: FontScheme;
}

export interface DxfFill {
  color?: Color;
}

export interface DxfBorderItem {
  style: BorderStyle;
  color?: Color;
}

export interface DxfBorder {
  diagonal_up?: boolean;
  diagonal_down?: boolean;
  left?: DxfBorderItem;
  right?: DxfBorderItem;
  top?: DxfBorderItem;
  bottom?: DxfBorderItem;
  diagonal?: DxfBorderItem;
}

export interface DxfNumFmt {
  num_fmt_id: number;
  format_code: string;
}

export interface DxfAlignment {
  horizontal?: HorizontalAlignment;
  vertical?: VerticalAlignment;
  wrap_text?: boolean;
}

export interface Dxf {
  font?: DxfFont;
  fill?: DxfFill;
  border?: DxfBorder;
  num_fmt?: DxfNumFmt;
  alignment?: DxfAlignment;
}

/** A CF rule plus its storage `index` in the worksheet's rule list, returned by
 * getConditionalFormattingList. The list is sorted by priority (descending), so
 * `index` — not the array position — must be used to address a rule in
 * getDxfForConditionalFormatting / updateConditionalFormatting /
 * deleteConditionalFormatting / raiseConditionalFormattingPriority /
 * lowerConditionalFormattingPriority. */
export interface ConditionalFormattingView {
  index: number;
  range: string;
  cf_rule: CfRule;
  priority: number;
}

export interface CfIcon {
  icon: Icon;
  color: Color;
  show_value: boolean;
}

export interface CfDataBar {
  positive_color: Color;
  negative_color: Color;
  is_gradient: boolean;
  value: number;
  axis_position: number;
  show_value: boolean;
}

export interface CfRating {
  icon: Icon;
  count: number;
  max: number;
  color: Color;
  show_value: boolean;
}

export interface ExtendedCellStyle {
  style: CellStyle;
  icon: CfIcon | null;
  data_bar: CfDataBar | null;
  rating: CfRating | null;
}

export interface SelectedView {
  sheet: number;
  row: number;
  column: number;
  range: [number, number, number, number];
  top_row: number;
  left_column: number;
}

export interface ClipboardCell {
  text: string;
  style: CellStyle;
}

/** Rows keyed by row number, each mapping column number to a cell. */
export type ClipboardData = Record<string, Record<string, ClipboardCell>>;

export interface Clipboard {
  csv: string;
  data: ClipboardData;
  range: [number, number, number, number];
}

export interface DefinedName {
  name: string;
  scope?: number;
  formula: string;
}

export interface FmtSettings {
  currency: string;
  currency_format: string;
  short_date: string;
  short_date_example: string;
  long_date: string;
  long_date_example: string;
  number_fmt: string;
  number_example: string;
}

/** The formatting categories a named style includes. */
export interface StyleIncludes {
  number_format: boolean;
  font: boolean;
  fill: boolean;
  border: boolean;
  alignment: boolean;
  protection: boolean;
}

/** A named cell style (e.g. "Normal", "Heading 1", or a custom style). */
export interface NamedStyle {
  /** The style name. */
  name: string;
  /** The full style definition. */
  style: CellStyle;
}

/** A workbook color theme. */
export interface IronCalcTheme {
  /** Display name, e.g. "Office", "Retrospect". */
  name: string;
  /** Dark 1 (text/background). */
  dk1: string;
  /** Light 1 (text/background). */
  lt1: string;
  /** Dark 2 (text/background). */
  dk2: string;
  /** Light 2 (text/background). */
  lt2: string;
  accent1: string;
  accent2: string;
  accent3: string;
  accent4: string;
  accent5: string;
  accent6: string;
  /** Hyperlink color. */
  hlink: string;
  /** Followed-hyperlink color. */
  fol_hlink: string;
}
/**
 * A workbook model implementing the "raw" low level API. Nothing is
 * evaluated automatically: you need to call `evaluate` yourself. There is no
 * undo/redo history and no diffs are produced.
 */
export declare class Model {
  /**
   * Creates an empty workbook. `locale`, `timezone` and `languageId` default
   * to "en", "UTC" and "en".
   */
  constructor(name: string, locale?: string | undefined | null, timezone?: string | undefined | null, languageId?: string | undefined | null)
  /** Creates a model from an xlsx file */
  static fromXlsx(filePath: string, locale?: string | undefined | null, timezone?: string | undefined | null, languageId?: string | undefined | null): Model
  /** Creates a model from an icalc file */
  static fromIcalc(fileName: string, languageId?: string | undefined | null): Model
  /**
   * Creates a model from bytes in the internal binary ic format.
   * This is the same format produced by `saveToIcalc` and `toBytes`.
   */
  static fromBytes(bytes: Uint8Array, languageId?: string | undefined | null): Model
  /** Saves the workbook to an xlsx file */
  saveToXlsx(file: string): void
  /** Saves the workbook to a file in the internal binary ic format */
  saveToIcalc(file: string): void
  /** Returns the workbook as bytes in the internal binary ic format */
  toBytes(): Uint8Array
  /** Evaluates the workbook */
  evaluate(): void
  /**
   * Sets an input in a cell, parsing it as a user would type it:
   * "3.5" is a number, "Hello" a string, "=A1*2" a formula
   */
  setUserInput(sheet: number, row: number, column: number, value: string): void
  /** Sets an array (spill) formula in the range */
  setUserArrayFormula(sheet: number, row: number, column: number, width: number, height: number, formula: string): void
  /** Sets a string value in a cell without input parsing */
  updateCellWithText(sheet: number, row: number, column: number, value: string): void
  /** Sets a number in a cell without input parsing */
  updateCellWithNumber(sheet: number, row: number, column: number, value: number): void
  /** Sets a boolean in a cell without input parsing */
  updateCellWithBool(sheet: number, row: number, column: number, value: boolean): void
  /** Sets a formula (i.e. "=A1*2") in a cell */
  updateCellWithFormula(sheet: number, row: number, column: number, formula: string): void
  /** Clears the contents of a single cell, keeping the formatting */
  clearCellContents(sheet: number, row: number, column: number): void
  /** Clears the contents of all cells in the range, keeping the formatting */
  rangeClearContents(sheet: number, startRow: number, startColumn: number, endRow: number, endColumn: number): void
  /** Clears contents and formatting of all cells in the range */
  rangeClearAll(sheet: number, startRow: number, startColumn: number, endRow: number, endColumn: number): void
  /**
   * Returns the content of a cell as the user would see it in the editor:
   * the formula if there is one or the raw value otherwise
   */
  getCellContent(sheet: number, row: number, column: number): string
  /** Returns the formula of a cell, if any */
  getCellFormula(sheet: number, row: number, column: number): string | null
  /**
   * Returns the value of a cell as a native JS value
   * (null, string, number or boolean)
   */
  getCellValue(sheet: number, row: number, column: number): number | string | boolean | null
  /**
   * Returns the value of a cell referenced like "Sheet1!C4" as a native JS
   * value (null, string, number or boolean)
   */
  getCellValueByRef(cellRef: string): number | string | boolean | null
  /** Returns the type of the content of a cell */
  getCellType(sheet: number, row: number, column: number): CellType
  /** Returns the formatted value of a cell (i.e. "$ 5.75") */
  getFormattedCellValue(sheet: number, row: number, column: number): string
  /** Returns true if the cell is empty */
  isEmptyCell(sheet: number, row: number, column: number): boolean
  /** Returns all non-empty cells as a list of [sheet, row, column] tuples */
  getAllCells(): Array<[number, number, number]>
  /** Returns a markdown-like representation of the sheet, useful for debugging */
  getSheetMarkup(sheet: number): string
  /** Sets the style of a cell from a style object */
  setCellStyle(sheet: number, row: number, column: number, style: CellStyle): void
  /** Returns the style of a cell */
  getCellStyle(sheet: number, row: number, column: number): CellStyle
  /** Sets the default style for a whole column */
  setColumnStyle(sheet: number, column: number, style: CellStyle): void
  /** Returns the default style of a column, if any */
  getColumnStyle(sheet: number, column: number): CellStyle | null
  /** Deletes the default style of a column */
  deleteColumnStyle(sheet: number, column: number): void
  /** Sets the default style for a whole row */
  setRowStyle(sheet: number, row: number, style: CellStyle): void
  /** Returns the default style of a row, if any */
  getRowStyle(sheet: number, row: number): CellStyle | null
  /** Deletes the default style of a row */
  deleteRowStyle(sheet: number, row: number): void
  insertRows(sheet: number, row: number, rowCount: number): void
  insertColumns(sheet: number, column: number, columnCount: number): void
  deleteRows(sheet: number, row: number, rowCount: number): void
  deleteColumns(sheet: number, column: number, columnCount: number): void
  /** Moves a column by `delta` positions */
  moveColumn(sheet: number, column: number, delta: number): void
  /** Moves a row by `delta` positions */
  moveRow(sheet: number, row: number, delta: number): void
  getColumnWidth(sheet: number, column: number): number
  getRowHeight(sheet: number, row: number): number
  setColumnWidth(sheet: number, column: number, width: number): void
  setRowHeight(sheet: number, row: number, height: number): void
  setColumnHidden(sheet: number, column: number, hidden: boolean): void
  setRowHidden(sheet: number, row: number, hidden: boolean): void
  isColumnHidden(sheet: number, column: number): boolean
  isRowHidden(sheet: number, row: number): boolean
  getFrozenColumnsCount(sheet: number): number
  getFrozenRowsCount(sheet: number): number
  setFrozenColumnsCount(sheet: number, columnCount: number): void
  setFrozenRowsCount(sheet: number, rowCount: number): void
  /** Returns the list of sheets with their properties (name, state, color, ...) */
  getWorksheetsProperties(): Array<WorksheetProperties>
  /** Sets the sheet tab color. Accepts null, "#RRGGBB" or [theme, tint] */
  setSheetColor(sheet: number, color?: Color | null): void
  /** Sets the sheet visibility state: "visible", "hidden" or "veryHidden" */
  setSheetState(sheet: number, state: string): void
  /** Adds a new sheet with the given name */
  addSheet(sheetName: string): void
  /** Adds a new sheet with an automatically generated name */
  newSheet(): void
  deleteSheet(sheet: number): void
  renameSheet(sheet: number, newName: string): void
  /**
   * Returns the bounds of all non-empty cells as
   * [minRow, maxRow, minColumn, maxColumn]. For an empty sheet returns [1, 1, 1, 1].
   */
  getSheetDimensions(sheet: number): [number, number, number, number]
  setShowGridLines(sheet: number, showGridLines: boolean): void
  /** Returns the list of defined names as [{name, scope, formula}] */
  getDefinedNameList(): Array<DefinedName>
  /** Creates a new defined name. `scope` is a sheet index or null for global scope. */
  newDefinedName(name: string, scope: number | undefined | null, formula: string): void
  updateDefinedName(name: string, scope: number | undefined | null, newName: string, newScope: number | undefined | null, newFormula: string): void
  deleteDefinedName(name: string, scope?: number | undefined | null): void
  /** Returns the workbook theme */
  getTheme(): IronCalcTheme
  /** Sets the workbook theme */
  setTheme(theme: IronCalcTheme): void
  getTimezone(): string
  setTimezone(timezone: string): void
  getLocale(): string
  setLocale(locale: string): void
  getLanguage(): string
  setLanguage(language: string): void
  /** Returns locale dependent formatting settings (currency, date formats, ...) */
  getFmtSettings(): FmtSettings
}

/**
 * A workbook model implementing the "user" API: the same high level API used
 * by the IronCalc web application. Every action evaluates the model, keeps
 * undo/redo history and produces diffs for collaboration.
 */
export declare class UserModel {
  /**
   * Creates an empty workbook. `locale`, `timezone` and `languageId` default
   * to "en", "UTC" and "en".
   */
  constructor(name: string, locale?: string | undefined | null, timezone?: string | undefined | null, languageId?: string | undefined | null)
  /** Creates a user model from bytes in the internal binary ic format */
  static fromBytes(bytes: Uint8Array, languageId?: string | undefined | null): UserModel
  /** Creates a user model from an xlsx file */
  static fromXlsx(filePath: string, locale?: string | undefined | null, timezone?: string | undefined | null, languageId?: string | undefined | null): UserModel
  /** Creates a user model from an icalc file */
  static fromIcalc(fileName: string, languageId?: string | undefined | null): UserModel
  /** Saves the workbook to an xlsx file */
  saveToXlsx(file: string): void
  /** Saves the workbook to a file in the internal binary ic format */
  saveToIcalc(file: string): void
  /** Returns the workbook as bytes in the internal binary ic format */
  toBytes(): Uint8Array
  /** Applies a list of diffs produced by another model's `flushSendQueue` */
  applyExternalDiffs(externalDiffs: Uint8Array): void
  /** Returns (and clears) the queue of diffs produced by local edits */
  flushSendQueue(): Uint8Array
  undo(): void
  redo(): void
  canUndo(): boolean
  canRedo(): boolean
  /** Pauses automatic evaluation after each change */
  pauseEvaluation(): void
  /** Resumes automatic evaluation after each change */
  resumeEvaluation(): void
  /** Forces an evaluation of the workbook (only needed while paused) */
  evaluate(): void
  /** Returns the name of the workbook */
  getName(): string
  /** Sets the name of the workbook */
  setName(name: string): void
  getTimezone(): string
  setTimezone(timezone: string): void
  getLocale(): string
  setLocale(locale: string): void
  getLanguage(): string
  setLanguage(language: string): void
  /** Returns locale dependent formatting settings (currency, date formats, ...) */
  getFmtSettings(): FmtSettings
  /** Returns the workbook theme */
  getTheme(): IronCalcTheme
  /** Sets the workbook theme */
  setTheme(theme: IronCalcTheme): void
  /**
   * Resolves a color (null, "#RRGGBB" or [theme, tint]) to a CSS hex string
   * using the current workbook theme. Returns "" for no color.
   */
  resolveColor(color?: Color | null): string
  /** Sets the user input in a cell: a value like "3.5", "Hello" or a formula like "=A1*2" */
  setUserInput(sheet: number, row: number, column: number, value: string): void
  /** Sets an array (spill) formula in the range */
  setUserArrayFormula(sheet: number, row: number, column: number, width: number, height: number, formula: string): void
  /**
   * Returns the content of a cell as the user would see it in the editor:
   * the formula if there is one or the raw value otherwise
   */
  getCellContent(sheet: number, row: number, column: number): string
  /** Returns the formatted value of a cell (i.e. "$ 5.75") */
  getFormattedCellValue(sheet: number, row: number, column: number): string
  /** Returns the type of the content of a cell */
  getCellType(sheet: number, row: number, column: number): CellType
  /** Returns information about the array (spill) structure of a cell */
  getCellArrayStructure(sheet: number, row: number, column: number): CellArrayStructure
  /**
   * Returns the bounds of all non-empty cells as
   * [minRow, maxRow, minColumn, maxColumn]. For an empty sheet returns [1, 1, 1, 1].
   */
  getSheetDimensions(sheet: number): [number, number, number, number]
  /** Clears contents and formatting of all cells in the range */
  rangeClearAll(sheet: number, startRow: number, startColumn: number, endRow: number, endColumn: number): void
  /** Clears the contents of all cells in the range, keeping the formatting */
  rangeClearContents(sheet: number, startRow: number, startColumn: number, endRow: number, endColumn: number): void
  /** Clears the formatting of all cells in the range, keeping the contents */
  rangeClearFormatting(sheet: number, startRow: number, startColumn: number, endRow: number, endColumn: number): void
  /** Extends the content of the source area downwards/upwards until `toRow` */
  autoFillRows(sheet: number, startRow: number, startColumn: number, endRow: number, endColumn: number, toRow: number): void
  /** Extends the content of the source area right/left until `toColumn` */
  autoFillColumns(sheet: number, startRow: number, startColumn: number, endRow: number, endColumn: number, toColumn: number): void
  /** Adds a new sheet with an automatically generated name */
  newSheet(): void
  deleteSheet(sheet: number): void
  duplicateSheet(sheet: number): void
  hideSheet(sheet: number): void
  unhideSheet(sheet: number): void
  renameSheet(sheet: number, name: string): void
  /** Moves the sheet to a new position in the list of sheets */
  moveSheet(sheet: number, newIndex: number): void
  /** Sets the sheet tab color. Accepts null, "#RRGGBB" or [theme, tint] */
  setSheetColor(sheet: number, color?: Color | null): void
  /** Returns the list of sheets with their properties (name, state, color, ...) */
  getWorksheetsProperties(): Array<WorksheetProperties>
  setShowGridLines(sheet: number, showGridLines: boolean): void
  getShowGridLines(sheet: number): boolean
  insertRows(sheet: number, row: number, rowCount: number): void
  insertColumns(sheet: number, column: number, columnCount: number): void
  deleteRows(sheet: number, row: number, rowCount: number): void
  deleteColumns(sheet: number, column: number, columnCount: number): void
  /** Moves `columnCount` columns starting at `column` by `delta` positions */
  moveColumns(sheet: number, column: number, columnCount: number, delta: number): void
  /** Moves `rowCount` rows starting at `row` by `delta` positions */
  moveRows(sheet: number, row: number, rowCount: number, delta: number): void
  getRowHeight(sheet: number, row: number): number
  getColumnWidth(sheet: number, column: number): number
  setRowsHeight(sheet: number, rowStart: number, rowEnd: number, height: number): void
  setColumnsWidth(sheet: number, columnStart: number, columnEnd: number, width: number): void
  setRowsHidden(sheet: number, rowStart: number, rowEnd: number, hidden: boolean): void
  setColumnsHidden(sheet: number, columnStart: number, columnEnd: number, hidden: boolean): void
  getFrozenRowsCount(sheet: number): number
  getFrozenColumnsCount(sheet: number): number
  setFrozenRowsCount(sheet: number, count: number): void
  setFrozenColumnsCount(sheet: number, count: number): void
  /** Returns the last non-empty column in the row before `column`, if any */
  getLastNonEmptyInRowBeforeColumn(sheet: number, row: number, column: number): number | null
  /** Returns the first non-empty column in the row after `column`, if any */
  getFirstNonEmptyInRowAfterColumn(sheet: number, row: number, column: number): number | null
  /**
   * Updates a single style property in all cells of the range.
   * `stylePath` examples: "font.b", "font.color", "fill.color",
   * "alignment.horizontal", "num_fmt". The value is always a string,
   * i.e. "true", "#FF5566", "center", "#,##0.00".
   */
  updateRangeStyle(sheet: number, startRow: number, startColumn: number, endRow: number, endColumn: number, stylePath: string, value: string): void
  /** Returns the style of a cell */
  getCellStyle(sheet: number, row: number, column: number): CellStyle
  /**
   * Returns the style of a cell together with any conditional formatting
   * decorations (icon, data bar, rating)
   */
  getExtendedCellStyle(sheet: number, row: number, column: number): ExtendedCellStyle
  /**
   * Pastes a matrix of styles (list of rows, each a list of style objects)
   * starting at the selected cell
   */
  onPasteStyles(styles: Array<Array<CellStyle>>): void
  /**
   * Applies a border to an area. `borderArea` is an object like
   * {item: {style: "thin", color: "#000000"}, type: "All"}
   */
  setAreaWithBorder(sheet: number, startRow: number, startColumn: number, endRow: number, endColumn: number, borderArea: BorderArea): void
  /** Returns the names of all named styles in the workbook */
  getNamedStyleList(): Array<string>
  /** Returns the style associated with the named style */
  getNamedStyle(name: string): CellStyle
  /** Returns which formatting categories the named style includes */
  getNamedStyleIncludes(name: string): StyleIncludes
  /**
   * Creates a new named style from a style object. `includes` selects
   * which formatting categories the style carries; null means all of them.
   */
  createNamedStyle(name: string, style: CellStyle, includes?: StyleIncludes | null): void
  /** Updates (and possibly renames) an existing named style */
  updateNamedStyle(name: string, newName: string, style: CellStyle, includes?: StyleIncludes | null): void
  deleteNamedStyle(name: string): void
  /** Returns all Excel built-in named styles as a list of {name, style} */
  getBuiltinNamedStyles(): Array<NamedStyle>
  /**
   * Applies a named style to the current selection.
   * If the style is a built-in not yet in the workbook, it is added first.
   */
  onApplyNamedStyle(name: string): void
  /** Returns the list of conditional formatting rules of the sheet */
  getConditionalFormattingList(sheet: number): Array<ConditionalFormattingView>
  /**
   * Adds a conditional formatting rule to a range like "A1:B10".
   * `rule` is an object, i.e. {type: "CellIs", operator: "GreaterThan",
   * formula: "5", format: {fill: {color: "#FF0000"}}}
   */
  addConditionalFormatting(sheet: number, range: string, rule: CfRuleInput): void
  /** Updates the conditional formatting rule at `index` */
  updateConditionalFormatting(sheet: number, index: number, newRange: string, newRule: CfRuleInput): void
  deleteConditionalFormatting(sheet: number, index: number): void
  /** Returns the differential style (dxf) applied by the rule at `index` */
  getDxfForConditionalFormatting(sheet: number, index: number): Dxf
  raiseConditionalFormattingPriority(sheet: number, index: number): void
  lowerConditionalFormattingPriority(sheet: number, index: number): void
  /** Returns the list of defined names as [{name, scope, formula}] */
  getDefinedNameList(): Array<DefinedName>
  /** Creates a new defined name. `scope` is a sheet index or null for global scope. */
  newDefinedName(name: string, scope: number | undefined | null, formula: string): void
  updateDefinedName(name: string, scope: number | undefined | null, newName: string, newScope: number | undefined | null, newFormula: string): void
  deleteDefinedName(name: string, scope?: number | undefined | null): void
  /** Throws if the defined name is not valid */
  isValidDefinedName(name: string, scope: number | undefined | null, formula: string): void
  getSelectedSheet(): number
  /** Returns the selected cell as [sheet, row, column] */
  getSelectedCell(): [number, number, number]
  /** Returns the selected view (sheet, selected range, top left visible cell, ...) */
  getSelectedView(): SelectedView
  setSelectedSheet(sheet: number): void
  setSelectedCell(row: number, column: number): void
  setSelectedRange(startRow: number, startColumn: number, endRow: number, endColumn: number): void
  /**
   * Copies the selected area, returning an object with the csv text,
   * the internal data and the copied range
   */
  copyToClipboard(): Clipboard
  /** Pastes data copied with `copyToClipboard` into the selected area */
  pasteFromClipboard(sourceSheet: number, sourceRange: [number, number, number, number], clipboard: ClipboardData, isCut: boolean): void
  /** Pastes a csv string starting at the top-left corner of the given area */
  pasteCsvString(sheet: number, startRow: number, startColumn: number, endRow: number, endColumn: number, csv: string): void
}

/** The type of the content of a cell, following Excel's TYPE() convention. */
export declare const enum CellType {
  Number = 1,
  Text = 2,
  LogicalValue = 4,
  ErrorValue = 16,
  Array = 64,
  CompoundData = 128
}

/** Returns the column name ("A", "B", ..., "XFD") for a column number (1-indexed) */
export declare function columnNameFromNumber(column: number): string

/** Returns the column number (1-indexed) for a column name ("A", "B", ..., "XFD") */
export declare function columnNumberFromName(column: string): number

/** Returns the list of all supported timezones */
export declare function getAllTimezones(): Array<string>

/** Returns the list of all supported locales */
export declare function getSupportedLocales(): Array<string>

/** Quotes a sheet name if needed so it can be used in a formula reference */
export declare function quoteName(name: string): string
