use crate::types::Theme;

pub fn builtin_themes() -> Vec<Theme> {
    vec![
        // Microsoft Office default: slate navy, warm orange, sky blue
        Theme {
            name: "Office".to_string(),
            dk1: "#000000".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#44546A".to_string(),
            lt2: "#E7E6E6".to_string(),
            accent1: "#4472C4".to_string(),
            accent2: "#ED7D31".to_string(),
            accent3: "#A5A5A5".to_string(),
            accent4: "#FFC000".to_string(),
            accent5: "#5B9BD5".to_string(),
            accent6: "#70AD47".to_string(),
            hlink: "#0563C1".to_string(),
            fol_hlink: "#954F72".to_string(),
        },
        // Retrospect: Muted red, earthy green, soft purple
        Theme {
            name: "Retrospect".to_string(),
            dk1: "#000000".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#3F3F3F".to_string(),
            lt2: "#EEECE1".to_string(),
            accent1: "#C0504D".to_string(),
            accent2: "#9BBB59".to_string(),
            accent3: "#8064A2".to_string(),
            accent4: "#4BACC6".to_string(),
            accent5: "#F79646".to_string(),
            accent6: "#7F7F7F".to_string(),
            hlink: "#C0504D".to_string(),
            fol_hlink: "#8064A2".to_string(),
        },
        // Facet: Vivid lime greens, gold, and orange-red pops
        Theme {
            name: "Facet".to_string(),
            dk1: "#000000".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#404040".to_string(),
            lt2: "#F2F2F2".to_string(),
            accent1: "#90C226".to_string(),
            accent2: "#54A021".to_string(),
            accent3: "#E6B91E".to_string(),
            accent4: "#E76618".to_string(),
            accent5: "#C42F2F".to_string(),
            accent6: "#917EAC".to_string(),
            hlink: "#0563C1".to_string(),
            fol_hlink: "#954F72".to_string(),
        },
        // Ion: Cool teals, ocean blues, and deep greens
        Theme {
            name: "Ion".to_string(),
            dk1: "#000000".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#0E5484".to_string(),
            lt2: "#E8F5FB".to_string(),
            accent1: "#1CADE4".to_string(),
            accent2: "#2683C6".to_string(),
            accent3: "#27CED7".to_string(),
            accent4: "#42BA97".to_string(),
            accent5: "#3E8853".to_string(),
            accent6: "#62A39F".to_string(),
            hlink: "#0563C1".to_string(),
            fol_hlink: "#954F72".to_string(),
        },
        // Metropolitan: Urban indigo, cerulean, and slate
        Theme {
            name: "Metropolitan".to_string(),
            dk1: "#000000".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#323E4F".to_string(),
            lt2: "#E8EBF0".to_string(),
            accent1: "#4763AB".to_string(),
            accent2: "#3A96CD".to_string(),
            accent3: "#66C9D5".to_string(),
            accent4: "#00AEAD".to_string(),
            accent5: "#499478".to_string(),
            accent6: "#5E6D73".to_string(),
            hlink: "#4763AB".to_string(),
            fol_hlink: "#499478".to_string(),
        },
    ]
}
