use crate::types::Theme;

pub fn builtin_themes() -> Vec<Theme> {
    vec![
        // IronCalc: teal, green, chartreuse, amber, orange, red
        Theme {
            name: "IronCalc".to_string(),
            dk1: "#272525".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#595555".to_string(),
            lt2: "#E8E8E8".to_string(),
            accent1: "#1B717E".to_string(),
            accent2: "#3BB68A".to_string(),
            accent3: "#8CB354".to_string(),
            accent4: "#F8CD3D".to_string(),
            accent5: "#F2994A".to_string(),
            accent6: "#EC5753".to_string(),
            hlink: "#1B717E".to_string(),
            fol_hlink: "#523E93".to_string(),
        },
        // Microsoft Office default: slate navy, warm orange, sky blue
        Theme {
            name: "Office".to_string(),
            dk1: "#000000".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#44546A".to_string(),
            lt2: "#E7E6E6".to_string(),
            accent1: "#4472C4".to_string(),
            accent2: "#ED7D31".to_string(),
            accent3: "#A5A5A5".to_string(),
            accent4: "#FFC000".to_string(),
            accent5: "#5B9BD5".to_string(),
            accent6: "#70AD47".to_string(),
            hlink: "#0563C1".to_string(),
            fol_hlink: "#954F72".to_string(),
        },
        // Greyscale: pure achromatic neutrals
        Theme {
            name: "Greyscale".to_string(),
            dk1: "#1A1A1A".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#2D2D2D".to_string(),
            lt2: "#F2F2F2".to_string(),
            accent1: "#333333".to_string(),
            accent2: "#4F4F4F".to_string(),
            accent3: "#828282".to_string(),
            accent4: "#BDBDBD".to_string(),
            accent5: "#E0E0E0".to_string(),
            accent6: "#F2F2F2".to_string(),
            hlink: "#4F4F4F".to_string(),
            fol_hlink: "#828282".to_string(),
        },
        // Cold: icy blues and steel
        Theme {
            name: "Cold".to_string(),
            dk1: "#1C1C1E".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#1A2B3C".to_string(),
            lt2: "#D6EBF2".to_string(),
            accent1: "#2E8BC0".to_string(),
            accent2: "#5FA8D3".to_string(),
            accent3: "#A6DCEF".to_string(),
            accent4: "#D6EBF2".to_string(),
            accent5: "#90ADC6".to_string(),
            accent6: "#547AA5".to_string(),
            hlink: "#2E8BC0".to_string(),
            fol_hlink: "#547AA5".to_string(),
        },
        // Warm: terracotta, amber, and burnt orange
        Theme {
            name: "Warm".to_string(),
            dk1: "#2E1A14".to_string(),
            lt1: "#FFF9F4".to_string(),
            dk2: "#3D2418".to_string(),
            lt2: "#F2E4D4".to_string(),
            accent1: "#C1440E".to_string(),
            accent2: "#F26800".to_string(),
            accent3: "#F89D13".to_string(),
            accent4: "#FFD56F".to_string(),
            accent5: "#DDA15E".to_string(),
            accent6: "#BC6C25".to_string(),
            hlink: "#C1440E".to_string(),
            fol_hlink: "#BC6C25".to_string(),
        },
        // Ocean: deep teals and aquamarines
        Theme {
            name: "Ocean".to_string(),
            dk1: "#00303D".to_string(),
            lt1: "#E6FCFF".to_string(),
            dk2: "#003D4D".to_string(),
            lt2: "#B3EEF5".to_string(),
            accent1: "#007C91".to_string(),
            accent2: "#00A6A6".to_string(),
            accent3: "#38B6B2".to_string(),
            accent4: "#A0E8E0".to_string(),
            accent5: "#58C9B9".to_string(),
            accent6: "#1C7C7D".to_string(),
            hlink: "#007C91".to_string(),
            fol_hlink: "#1C7C7D".to_string(),
        },
        // Pastel: soft candy tones on white
        Theme {
            name: "Pastel".to_string(),
            dk1: "#2E2E2E".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#3A3A3A".to_string(),
            lt2: "#F0F0F0".to_string(),
            accent1: "#F6A6B2".to_string(),
            accent2: "#FFD1DC".to_string(),
            accent3: "#B4E1FF".to_string(),
            accent4: "#D7F9F1".to_string(),
            accent5: "#FFF5BA".to_string(),
            accent6: "#C3F584".to_string(),
            hlink: "#F6A6B2".to_string(),
            fol_hlink: "#B4E1FF".to_string(),
        },
        // Dark: inverted base with vivid neon-adjacent accents
        Theme {
            name: "Dark".to_string(),
            dk1: "#FFFFFF".to_string(),
            lt1: "#333333".to_string(),
            dk2: "#CCCCCC".to_string(),
            lt2: "#1A1A1A".to_string(),
            accent1: "#4ECDC4".to_string(),
            accent2: "#3A86FF".to_string(),
            accent3: "#8338EC".to_string(),
            accent4: "#FF006E".to_string(),
            accent5: "#F2994A".to_string(),
            accent6: "#FFBE0B".to_string(),
            hlink: "#3A86FF".to_string(),
            fol_hlink: "#8338EC".to_string(),
        },
        // Forest: mossy greens, parchment, earthy accents
        Theme {
            name: "Forest".to_string(),
            dk1: "#1E2A1E".to_string(),
            lt1: "#F4F1EA".to_string(),
            dk2: "#243024".to_string(),
            lt2: "#E6E0D0".to_string(),
            accent1: "#3A6B35".to_string(),
            accent2: "#7DAB5F".to_string(),
            accent3: "#C8A84B".to_string(),
            accent4: "#B85C38".to_string(),
            accent5: "#8B6F47".to_string(),
            accent6: "#5C8A5E".to_string(),
            hlink: "#3A6B35".to_string(),
            fol_hlink: "#B85C38".to_string(),
        },
    ]
}
