use crate::types::Theme;

pub fn builtin_themes() -> Vec<Theme> {
    vec![
        // IronCalc: branding palette
        Theme {
            name: "IronCalc".to_string(),
            dk1: "#272525".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#333333".to_string(),
            lt2: "#F8F4F1".to_string(),
            accent1: "#8CB354".to_string(),
            accent2: "#F8CD3D".to_string(),
            accent3: "#F2994A".to_string(),
            accent4: "#EC5753".to_string(),
            accent5: "#523E93".to_string(),
            accent6: "#3458B7".to_string(),
            hlink: "#F2994A".to_string(),
            fol_hlink: "#843BBC".to_string(),
        },
        // Microsoft Office default: slate navy, warm orange, sky blue
        Theme {
            name: "Office".to_string(),
            dk1: "#000000".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#44546A".to_string(),
            lt2: "#E7E6E6".to_string(),
            accent1: "#4472C4".to_string(),
            accent2: "#ED7D31".to_string(),
            accent3: "#A5A5A5".to_string(),
            accent4: "#FFC000".to_string(),
            accent5: "#5B9BD5".to_string(),
            accent6: "#70AD47".to_string(),
            hlink: "#0563C1".to_string(),
            fol_hlink: "#954F72".to_string(),
        },
        // Cold: icy blues and steel
        Theme {
            name: "Cold".to_string(),
            dk1: "#1C1C1E".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#283640".to_string(),
            lt2: "#F2F7FA".to_string(),
            accent1: "#2E8BC0".to_string(),
            accent2: "#5FA8D3".to_string(),
            accent3: "#A6DCEF".to_string(),
            accent4: "#D6EBF2".to_string(),
            accent5: "#90ADC6".to_string(),
            accent6: "#547AA5".to_string(),
            hlink: "#843BBC".to_string(),
            fol_hlink: "#B984E2".to_string(),
        },
        // Warm: terracotta, amber, and burnt orange
        Theme {
            name: "Warm".to_string(),
            dk1: "#272525".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#2E1D0B".to_string(),
            lt2: "#FDFAF6".to_string(),
            accent1: "#C1440E".to_string(),
            accent2: "#F26800".to_string(),
            accent3: "#F89D13".to_string(),
            accent4: "#FFD56F".to_string(),
            accent5: "#DDA15E".to_string(),
            accent6: "#8D4B1F".to_string(),
            hlink: "#4C4B63".to_string(),
            fol_hlink: "#9190AD".to_string(),
        },
        // Ocean: deep teals and aquamarines
        Theme {
            name: "Ocean".to_string(),
            dk1: "#001A21".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#123637".to_string(),
            lt2: "#F4FBFB".to_string(),
            accent1: "#007C91".to_string(),
            accent2: "#00A6A6".to_string(),
            accent3: "#58C9B9".to_string(),
            accent4: "#A0E8E0".to_string(),
            accent5: "#44BFC8".to_string(),
            accent6: "#1C7C7D".to_string(),
            hlink: "#7D1C58".to_string(),
            fol_hlink: "#994B7B".to_string(),
        },
        // Pastel: soft candy tones on white
        Theme {
            name: "Pastel".to_string(),
            dk1: "#2E2E2E".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#434742".to_string(),
            lt2: "#FBF5FB".to_string(),
            accent1: "#FFD1DC".to_string(),
            accent2: "#B4E1FF".to_string(),
            accent3: "#FFF5BA".to_string(),
            accent4: "#C3F584".to_string(),
            accent5: "#D2C6F2".to_string(),
            accent6: "#D7F9F1".to_string(),
            hlink: "#F6A6B2".to_string(),
            fol_hlink: "#C9A6F6".to_string(),
        },
        // Contrast: inverted base with vivid neon-adjacent accents
        Theme {
            name: "Contrast".to_string(),
            dk1: "#272525".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#373F3E".to_string(),
            lt2: "#F0F6F6".to_string(),
            accent1: "#4ECDC4".to_string(),
            accent2: "#3A86FF".to_string(),
            accent3: "#8338EC".to_string(),
            accent4: "#FF006E".to_string(),
            accent5: "#FB8822".to_string(),
            accent6: "#FFDA0B".to_string(),
            hlink: "#FB8822".to_string(),
            fol_hlink: "#8338EC".to_string(),
        },
        // Forest: mossy greens, parchment, earthy accents
        Theme {
            name: "Forest".to_string(),
            dk1: "#272525".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#28281E".to_string(),
            lt2: "#F6F6ED".to_string(),
            accent1: "#3A6B35".to_string(),
            accent2: "#7DAB5F".to_string(),
            accent3: "#C8A84B".to_string(),
            accent4: "#B85C38".to_string(),
            accent5: "#8C6F48".to_string(),
            accent6: "#5A462B".to_string(),
            hlink: "#3F88C5".to_string(),
            fol_hlink: "#86AFD2".to_string(),
        },
        // Greyscale: pure achromatic neutrals
        Theme {
            name: "Greyscale".to_string(),
            dk1: "#000000".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#272525".to_string(),
            lt2: "#F5F5F5".to_string(),
            accent1: "#333333".to_string(),
            accent2: "#4F4F4F".to_string(),
            accent3: "#828282".to_string(),
            accent4: "#BDBDBD".to_string(),
            accent5: "#E0E0E0".to_string(),
            accent6: "#F2F2F2".to_string(),
            hlink: "#4F4F4F".to_string(),
            fol_hlink: "#808080".to_string(),
        },
        // Sunshine: oranges and golden yellows on warm cream
        Theme {
            name: "Sunshine".to_string(),
            dk1: "#1E1400".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#493502".to_string(),
            lt2: "#F7F4EE".to_string(),
            accent1: "#FF7C01".to_string(),
            accent2: "#FF9502".to_string(),
            accent3: "#FFAA01".to_string(),
            accent4: "#FFC400".to_string(),
            accent5: "#FFDD03".to_string(),
            accent6: "#FFEC18".to_string(),
            hlink: "#2872FD".to_string(),
            fol_hlink: "#AC2CFB".to_string(),
        },
        // Emerald: forest greens and sage on ivory
        Theme {
            name: "Emerald".to_string(),
            dk1: "#11160D".to_string(),
            lt1: "#FFFFFF".to_string(),
            dk2: "#303C22".to_string(),
            lt2: "#F3F7EF".to_string(),
            accent1: "#5C8148".to_string(),
            accent2: "#76A45B".to_string(),
            accent3: "#8BB650".to_string(),
            accent4: "#A2C181".to_string(),
            accent5: "#D6ED89".to_string(),
            accent6: "#B3E093".to_string(),
            hlink: "#5A462B".to_string(),
            fol_hlink: "#98794E".to_string(),
        },
    ]
}
